# Generated by Django 3.2.4 on 2021-06-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('project_name', models.CharField(max_length=100, null=True)),
                ('subtitle', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('links', models.CharField(max_length=2000, null=True)),
                ('contact', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
